name: Sentry Metadata action
description: Sentry Metadata Action for Docker Buildx Bake.
author: Soramitsu Khmer Labs

branding:
  color: red
  icon: alert-triangle

inputs:
  sentry_url:
    description: Sentry URL
    default:  https://sentry.sorakh.app
    required: false
  sentry_org:
    description: Sentry Organization
    default:  soramitsukhmer
    required: false
  sentry_auth_token:
    description: Sentry Auth Token
    required: true

outputs:
  bake-file:
    description: Bake definiton file
    value: ${{ steps.meta.outputs.bake-file }}

runs:
  using: composite
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: GitHub Metadata action
      id: meta
      run: sentry-metadata-action.sh "${{ inputs.sentry_url }}" "${{ inputs.sentry_org }}" "${{ inputs.sentry_auth_token }}"
      shell: bash
